version: "3.3"

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        restart: unless-stopped
        networks:
            - magnit
        ports:
            - ${FRONTEND_PORT:-80}:80

    backend:
        image: node:10-alpine
        build: .
        volumes:
            - .:/devel
        working_dir: /devel/packages/backend
        command: npm run start:dev
        environment:
            - BACKEND_PORT=${BACKEND_PORT:-1337}
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - GLOBAL_CONTROLLER_PREFIX=${GLOBAL_CONTROLLER_PREFIX:-v1}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
            - POSTGRES_USER=${POSTGRES_USER:-magnit}
            - POSTGRES_HOST=${POSTGRES_HOST:-db}
            - POSTGRES_DB=${POSTGRES_DB:-magnit}
        restart: unless-stopped
        networks:
            - magnit
        ports:
            - ${BACKEND_PORT:-1337}:1337
        depends_on:
            - db

    db:
        image: postgres:11-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-magnit}
            - POSTGRES_DB=${POSTGRES_DB:-magnit}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
        networks:
            - magnit
        ports:
            - ${POSTGRES_PORT:-5432}:5432

networks:
    magnit:
