version: "3.3"

services:
    frontend:
        image: node:10-alpine
        build: .
        volumes:
            - .:/devel
        working_dir: /devel/packages/frontend
        command: npm run start
        restart: unless-stopped
        environment:
            - NODE_ENV=development
            - REACT_APP_BACKEND_URL=http://${REACT_APP_BACKEND_URL:-localhost}:${BACKEND_PORT:-1337}
        networks:
            - magnit
        depends_on:
            - backend
        ports:
            - ${FRONTEND_PORT:-3100}:3000

    backend:
        image: node:10-alpine
        build: .
        volumes:
            - .:/devel
        working_dir: /devel/packages/backend
        command: npm run start:dev
        environment:
            - AIRWATCH_AUTH=${AIRWATCH_AUTH}
            - AIRWATCH_BASE_URL=${AIRWATCH_BASE_URL}
            - AIRWATCH_TENANT_CODE=${AIRWATCH_TENANT_CODE}
            - AUTH_EXPIRES_IN=${AUTH_EXPIRES_IN:-1h}
            - AUTH_SECRET=${AUTH_SECRET}
            - NODE_ENV=development
            - BACKEND_PORT=${BACKEND_PORT:-1337}
            - BACKEND_HOST=${BACKEND_HOST:-http://localhost:${BACKEND_PORT:-1337}}
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - GLOBAL_CONTROLLER_PREFIX=${GLOBAL_CONTROLLER_PREFIX:-v1}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
            - POSTGRES_USER=${POSTGRES_USER:-magnit}
            - POSTGRES_HOST=${POSTGRES_HOST:-db}
            - POSTGRES_DB=${POSTGRES_DB:-magnit}
            - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
            - RABBITMQ_PORT=${RABBITMQ_PORT:-5762}
            - RABBITMQ_USER=${RABBITMQ_USER:-magnit}
            - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-magnit}
        restart: unless-stopped
        networks:
            - magnit
        ports:
            - ${BACKEND_PORT:-1337}:${BACKEND_PORT:-1337}
        depends_on:
            - db
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3.7-alpine
        restart: unless-stopped
        ports:
            - ${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-magnit}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-magnit}
        networks:
            - magnit

    db:
        image: postgres:11-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-magnit}
            - POSTGRES_DB=${POSTGRES_DB:-magnit}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
        networks:
            - magnit
        ports:
            - ${POSTGRES_PORT:-5432}:5432

networks:
    magnit:
