version: "3.3"

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        restart: unless-stopped
        networks:
            - magnit
        ports:
            - ${FRONTEND_PORT:-80}:80

    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
            args:
                - BACKEND_PORT=${BACKEND_PORT:-1337}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
                - SECRET=${SECRET:-magnit}
        restart: unless-stopped
        networks:
            - magnit
        ports:
            - ${BACKEND_PORT:-1337}:1337
        depends_on:
            - db

    db:
        image: postgres:11-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=magnit
            - POSTGRES_DB=magnit
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
        volumes:
            - ./packages/backend/stuff:/docker-entrypoint-initdb.d
        networks:
            - magnit
        ports:
            - 5432:5432

networks:
    magnit:
