version: "3.3"

services:
    amqp:
        image: rabbitmq:3.7-alpine
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-magnit}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-magnit}
        networks:
            - magnit
        volumes:
            - amqp:/var/lib/rabbitmq/mnesia

    db:
        image: postgres:11-alpine
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-magnit}
            - POSTGRES_DB=${POSTGRES_DB:-magnit}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
        networks:
            - magnit
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    amqp:
        external:
            name: magnit-amqp
    db:
        external:
            name: magnit-db

networks:
    magnit:
        external:
            name: magnit
