version: "3.3"

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        restart: unless-stopped
        networks:
            - magnit
        environment:
            - NODE_ENV=production
            - REACT_APP_BACKEND_URL=http://${REACT_APP_BACKEND_URL:-localhost}:${BACKEND_PORT:-1337}
        depends_on:
            - backend
            - db
        ports:
            - ${FRONTEND_PORT:-80}:80

    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        environment:
            - NODE_ENV=production
            - BACKEND_PORT=${BACKEND_PORT:-1337}
            - BACKEND_HOST=${BACKEND_HOST:-http://localhost:${BACKEND_PORT:-1337}}
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - GLOBAL_CONTROLLER_PREFIX=${GLOBAL_CONTROLLER_PREFIX:-v1}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
            - POSTGRES_USER=${POSTGRES_USER:-magnit}
            - POSTGRES_HOST=${POSTGRES_HOST:-db}
            - POSTGRES_DB=${POSTGRES_DB:-magnit}
            - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
            - RABBITMQ_PORT=${RABBITMQ_PORT:-5762}
            - RABBITMQ_USER=${RABBITMQ_USER:-magnit}
            - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-magnit}
        restart: unless-stopped
        networks:
            - magnit
        ports:
            - ${BACKEND_PORT:-1337}:${BACKEND_PORT:-1337}
        depends_on:
            - rabbitmq
            - db
        volumes:
            - ${BACKEND_LOGS_DIR}:/var/www/magnit/logs

    rabbitmq:
        image: rabbitmq:3.7-alpine
        restart: unless-stopped
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-magnit}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-magnit}
        networks:
            - magnit

    db:
        image: postgres:11-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-magnit}
            - POSTGRES_DB=${POSTGRES_DB:-magnit}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
        networks:
            - magnit
        volumes:
            - ${POSTGRES_DATA}:/var/lib/postgresql/data

networks:
    magnit:
