name: Node CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: yarn install --non-interactive --no-progress --skip-integrity-check --frozen-lockfile
            - name: Run libs build
              run: yarn build:lib
            - name: Run CRA build
              working-directory: ./frontend
              run: yarn build:no-lib
            - name: Run backend unit tests with coverage
              working-directory: ./backend
              run: yarn test:cov
            - name: Run backend e2e tests
              working-directory: ./end
              run: yarn test:e2e
              env:
                  CI: true
